Opozee.Server/Controllers/Admin/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Opozee.Models.API;
using Opozee.Models.Models;
using PagedList;
namespace opozee.Controllers.Admin
{
    public class QuestionsController : Controller
    {
        private OpozeeDbEntities db = new OpozeeDbEntities();

        // GET: Questions
        public ActionResult Index(int? userId, string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.QuestionSortParm = String.IsNullOrEmpty(sortOrder) ? "question_desc" : "";
            ViewBag.HashSortParm = String.IsNullOrEmpty(sortOrder) ? "hashtags_desc" : "";
            ViewBag.UserNameSortParm = String.IsNullOrEmpty(sortOrder) ? "user_desc" : "";
            ViewBag.LinkSortParm = String.IsNullOrEmpty(sortOrder) ? "link_desc" : "";
            ViewBag.DetailSortParm = String.IsNullOrEmpty(sortOrder) ? "link_desc" : "";

            ViewBag.UserId = userId;
            ViewBag.DateSortParm = sortOrder == "date" ? "date_desc" : "date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var questList = new List<PostQuestionDetail>();
            if (userId != null)
            {
                questList = (from q in db.Questions
                             join u in db.Users on q.OwnerUserID equals u.UserID
                             where u.UserID == userId
                             select new PostQuestionDetail
                             {
                                 Id = q.Id,
                                 Question = q.PostQuestion,
                                 OwnerUserID = q.OwnerUserID,
                                 OwnerUserName = u.UserName,
                                 //UserImage = string.IsNullOrEmpty(u.ImageURL) ? "" : u.ImageURL,
                                 HashTags = q.HashTags,
                                 CreationDate = q.CreationDate,
                                 Link= q.Link
                                 
                             }).ToList();
            }
            else
            {
                questList = (from q in db.Questions
                             join u in db.Users on q.OwnerUserID equals u.UserID
                             select new PostQuestionDetail
                             {
                                 Id = q.Id,
                                 Question = q.PostQuestion,
                                 OwnerUserID = q.OwnerUserID,
                                 OwnerUserName = u.UserName,
                                 //UserImage = string.IsNullOrEmpty(u.ImageURL) ? "" : u.ImageURL,
                                 HashTags = q.HashTags,
                                 CreationDate = q.CreationDate,
                                 Link=q.Link
                             }).ToList();
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                questList = questList.Where(s => s.Question.Contains(searchString)).ToList();
            }
            switch (sortOrder)
            {

                case "question_desc":
                    questList = questList.OrderByDescending(s => s.Question).ToList();
                    break;
                case "hashtags_desc":
                    questList = questList.OrderByDescending(s => s.HashTags).ToList();
                    break;
                case "hashtags":
                    questList = questList.OrderBy(s => s.HashTags).ToList();
                    break;
                case "user_desc":
                    questList = questList.OrderByDescending(s => s.OwnerUserName).ToList();
                    break;
                case "user":
                    questList = questList.OrderBy(s => s.OwnerUserName).ToList();
                    break;
                case "date":
                    questList = questList.OrderBy(s => s.CreationDate).ToList();
                    break;
                case "date_desc":
                    questList = questList.OrderByDescending(s => s.CreationDate).ToList();
                    break;
                case "link_desc":
                    questList = questList.OrderByDescending(s => s.Link).ToList();
                    break;
               
                default:  // Name ascending 
                    questList = questList.OrderBy(s => s.Question).ToList();
                    break;
            }

            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(questList.ToPagedList(pageNumber, pageSize));
            //return View(questList);
        }


        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            //var customerList = GetUsers();
            //PostQuestion post = new PostQuestion();
            //post.UserName = customerList.ToList();
            //return View(customerList);
            return View();
        }
        private IEnumerable<SelectListItem> GetUsers()
        {
            //OpozeeDbEntities entities = new OpozeeDbEntities();
            //List<SelectListItem> userList = (from p in entities.Users.Where(p => p.IsAdmin == false).AsEnumerable()
            //                                     select new SelectListItem
            //                                     {
            //                                         Text = p.UserName,
            //                                         Value = p.UserID.ToString()
            //                                     }).ToList();


            ////Add Default Item at First Position.
            //userList.Insert(0, new SelectListItem { Text = "--Select User--", Value = "" });
            //return SelectList(userList);
            using (var context = new OpozeeDbEntities())
            {
                List<SelectListItem> countries = context.Users.AsNoTracking()
                    .OrderBy(n => n.UserName)
                        .Select(n =>
                        new SelectListItem
                        {
                            Value = n.UserID.ToString(),
                            Text = n.UserName
                        }).ToList();
                var countrytip = new SelectListItem()
                {
                    Value = null,
                    Text = "--- select country ---"
                };
                countries.Insert(0, countrytip);
                return new SelectList(countries, "Value", "Text");
            }
        }
        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PostQuestion,OwnerUserID,HashTags,CreationDate,ModifiedDate")] Question question)
        {
            if (ModelState.IsValid)
            {
                question.CreationDate = DateTime.Now;
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Question question = db.Questions.Find(id);
            PostQuestion question = (from q in db.Questions
                                     join u in db.Users on q.OwnerUserID equals u.UserID
                                     where q.Id == id
                                     select new PostQuestion
                                     {
                                         Id = q.Id,
                                         Question = q.PostQuestion,
                                         OwnerUserID = q.OwnerUserID,
                                         OwnerUserName = u.UserName,
                                         HashTags = q.HashTags,
                                         Link=q.Link,
                                         Detail=q.Detail
                                     }).FirstOrDefault();
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PostQuestion postQuestion)
        {
            if (ModelState.IsValid)
            {
                Question question = new Question();
                question.PostQuestion = postQuestion.Question;
                question.HashTags = postQuestion.HashTags;
                question.Id = postQuestion.Id;
                question.ModifiedDate = DateTime.Now;
                question.OwnerUserID = postQuestion.OwnerUserID;
                question.Detail= postQuestion.Detail;
                question.Link = postQuestion.Link;

Opozee.Server/Views/Questions/Create.cshtml
@model Opozee.Models.API.PostQuestion

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create Question</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerUserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerUserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerUserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HashTags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HashTags, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HashTags, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.CreationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit"  class="btn btn-primary" >Submit</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Opozee.Server/Views/Questions/Delete.cshtml
@model Opozee.Models.Models.Question

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PostQuestion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostQuestion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerUserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerUserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HashTags)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HashTags)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Opozee.Server/Views/Questions/Details.cshtml
@model Opozee.Models.Models.Question

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details Question</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PostQuestion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostQuestion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerUserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerUserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HashTags)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HashTags)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Opozee.Server/Views/Questions/Edit.cshtml
@model Opozee.Models.API.PostQuestion

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit Question</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.OwnerUserID)

    <div class="form-group">
        @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OwnerUserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OwnerUserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OwnerUserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HashTags, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HashTags, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HashTags, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Detail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Detail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Detail, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.CreationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" value="Save" class="btn btn-primary">Save</button>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Opozee.Server/Views/Questions/Index.cshtml
@model PagedList.IPagedList<Opozee.Models.API.PostQuestionDetail>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Posted Questions</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Questions", FormMethod.Get))
{
    <div class="input-group">
        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { htmlAttributes = new { @class = "form-control bg-light border-0 small", @placeholder = "Search for..." } })
        <div class="input-group-append">
            <button class="btn btn-primary" type="submit">
                <i class="fas fa-search fa-sm"></i>
            </button>
        </div>
    </div>
}
<br />
<div class="card shadow mb-4">
    @*<div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>*@
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        @*<th>
            @Html.DisplayNameFor(model => model.Question)
        </th>*@
                        <th>
                            @Html.ActionLink("Question", "Index", new { userId = ViewBag.UserId, sortOrder = ViewBag.QuestionSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>
                        @*<th>
            @Html.DisplayNameFor(model => model.OwnerUserName)
        </th>*@
                        <th>
                            @Html.ActionLink("UserName", "Index", new { userId = ViewBag.UserId, sortOrder = ViewBag.UserNameSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>
                        @*<th>
            @Html.DisplayNameFor(model => model.HashTags)
        </th>*@
                        <th>
                            @Html.ActionLink("HashTags", "Index", new { userId = ViewBag.UserId, sortOrder = ViewBag.HashSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>
                        @*<th>
            @Html.DisplayNameFor(model => model.OwnerUserName)
        </th>*@
                        @*<th>
            @Html.DisplayNameFor(model => model.CreationDate)
        </th>*@
                        <th>
                            @Html.ActionLink("Link", "Index", new { userId = ViewBag.UserId, sortOrder = ViewBag.LinkSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>
 
                        <th>
                            @Html.ActionLink("CreationDate", "Index", new { userId = ViewBag.UserId, sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>
                        @*<th>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </th>*@
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Question)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OwnerUserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.HashTags)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreationDate)
                            </td>
                            @*<td>
                                    @Html.DisplayFor(modelItem => item.ModifiedDate)
                                </td>*@
                            <td>
                                @*@Html.ActionLink("Edit", "Edit", new { id = item.Id })*@
                                <a href="@Url.Action("Edit/"+item.Id )"><i class="fa fa-pencil" aria-hidden="true"></i></a> |
                                @*@Html.ActionLink("Details", "Details", new { id = item.Id })*@
                                <a href="@Url.Action("Details/"+item.Id )"><i class="fa fa-eye" aria-hidden="true"></i></a>|
                                @*@Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
                                <a href="@Url.Action("DeleteConfirmed/"+item.Id )" class="delete-link"><i class="fa fa-trash" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>

            <br />
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("Index",
                new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
        </div>
    </div>
</div>


<div id="delete-dialog" title="Confirmation" style="display:none;">
    <p>Are you sure you want to delete this Question?</p>
</div>